# Отчёт о выполнении лабораторной работы

Дописала недостоющие методы градиентного спуска - функция *gradient_descent* в модуле *optimization* и процедуры линейного поиска - метод *line_search* в классе *LineSearchTool* в модуле *optimization*.

Сделала оракул логистической регрессии (класс LogRegL2Oracle в модуле oracles). Еще сделала реализацию вспомогательной функции create_log_reg_oracle в модуле oracles

Написала подсчет разностных производных (функции grad_finite_diff и hess_finite_diff в модуле oracles).

Реализовала метод Ньютона (функция newton в модуле optimization)

# 3.1 Эксперимент: Траектория градиентного спуска на квадратичной функции

Проанализируйте траекторию градиентного спуска для нескольких квадратичных функций: при думайте две-три квадратичныедвумерныефункции, на которых работа метода будет отличаться, нарисуйте графики с линиями уровня функций и траекториями методов.  

Попробуйте ответить на следующий вопрос:Как отличается поведение метода в зависимости от числа обусловленности функции, выбора начальной точки и стратегии выбора шага (константная стратегия, Армихо, Вульф)?

Для рисования линий уровня можете воспользоваться функцией `plot_levels`, а для рисования траекторий `plot_trajectory` из файла `plot_trajectory_2d.py`, прилагающегося к заданию. Также обратите внимание, что оракул квадратичной функции `QuadraticOracle` уже реализован в модуле `oracles`. Он реализует функцию $f(x) = (1/2)〈Ax, x〉−〈b, x〉$, где $A∈S^n_{++}, b ∈ R^n$.

In [1]:
import numpy as np
import scipy
import matplotlib.pyplot as plt
import oracles
import optimization
import presubmit_tests as pt
from plot_trajectory_2d import plot_levels, plot_trajectory
from sklearn.datasets import load_svmlight_file

In [2]:
A = np.array([[1, 2], [3, -4]])
b = np.array([10, 11])
regcoef = 2
oracle = oracles.create_log_reg_oracle(A, b, regcoef)
f = lambda x: oracle.func(x)
x = np.array([1, 2])

for x in np.array([[1, 2], [-1, -2], [3, 0]]):
    print('x =', x)
    print('Градиент через grad:', oracle.grad(x))
    print('Градиент через grad_finite_diff:', oracles.grad_finite_diff(f, x))
    print('Гессиан через hess:')
    print(oracle.hess(x))
    print('Гессиан через hess_finite_diff')
    print(oracles.hess_finite_diff(f, x))
    print()

x = [1 2]
Градиент через grad: [-14.5  26. ]
Градиент через grad_finite_diff: [-14.50000013  25.99999931]
Гессиан через hess:
[[ 2.00000000e+00 -7.79748855e-24]
 [-7.79748855e-24  2.00000000e+00]]
Гессиан через hess_finite_diff
[[ 2.00003569e+00 -7.10542736e-05]
 [-7.10542736e-05  1.99989358e+00]]

x = [-1 -2]
Градиент через grad: [ -7. -14.]
Градиент через grad_finite_diff: [ -6.99999987 -14.00000009]
Гессиан через hess:
[[2.00000000e+00 1.92874985e-22]
 [1.92874985e-22 2.00000000e+00]]
Гессиан через hess_finite_diff
[[1.99996464 0.        ]
 [0.         2.00000017]]

x = [3 0]
Градиент через grad: [ 6.00000000e+00 -9.34807787e-13]
Градиент через grad_finite_diff: [5.99999996 0.        ]
Гессиан через hess:
[[2.00000000e+00 9.34807787e-14]
 [9.34807787e-14 2.00000000e+00]]
Гессиан через hess_finite_diff
[[2.00001793e+00 1.77635684e-05]
 [1.77635684e-05 2.00000017e+00]]



In [3]:
pt.test_python3()
pt.test_QuadraticOracle()
pt.test_log_reg_usual()
pt.test_log_reg_oracle_calls()
pt.test_grad_finite_diff_1()
pt.test_grad_finite_diff_2()
pt.test_hess_finite_diff_1()
pt.test_hess_finite_diff_2()
pt.test_line_search()
pt.test_gd_basic()
pt.test_newton_basic()
pt.test_newton_1d()
pt.test_newton_fail()

AssertionError: 16.0 != 32.0 within 7 places (16.0 difference)

Мы реализуем вычисление разностных производных с помощью функций `grad_finite_diff` и `hess_finite_diff` в модуле oracles. Для проверки корректности расчета градиента и гессиана в логистическом оракуле воспользуемся этими функциями. Сгенерируем небольшую модельную выборку (матрицу A и вектор b) и сравним результаты методов `grad` и `hess` с соответствующими разностными аппроксимациями в нескольких тестовых точках x.

Проанализируем поведение градиентного спуска на нескольких квадратичных функциях: зададим две-три двумерные квадратичные функции, для которых работа метода будет различаться, и построим графики с уровнями функций и траекториями движения методов.